### ISSUE TITLE
Provide an example scene?

### ISSUE THREAD

**Issue by mwalk-dev** [hudmarc/FFO-FishNet-Floating-Origin#1]
I have followed the steps in the README but have not been able to get the package working. It would be really helpful if a working example scene was included to compare against.

I have added this package to a barebones FishNet v2.6.2 project that works correctly with a host and client. Per the README I have replaced my existing `NetworkManager` with the FO prefab and added a `FOObserver` component to my player prefab. I've also added a `PlayerSpawner` component to the `NetworkManager`.

I'm seeing that the players are not kept at the origin (Unity position == real position up to a distance of ~1k from origin). After moving ~1k units away from origin the reported real position and group offset increase forever, even when the player has stopped moving, and the player prefab's Unity position is still not reset to origin.

**Comment by hudmarc** [comment]
Is there an Offsetter on the manager, and is that Offsetter correctly referenced on the manager? My prefab links broke while exporting and I thought I fixed it but maybe not...? What version of Unity are you testing in?

**Comment by hudmarc** [comment]
I just set up the scene like you described and it seems to work correctly on my end. I have added the FO provided Network Manager, and a Player Spawner component to that NetworkManager. This player is the default FishNet capsule set to a 1000x move rate on a huge plane. Whenever the player goes too far from the origin they are rebased. Is Auto Register set to true on your FOObserver?
Also, the player will not stay at 0,0,0 always, they are only rebased when they stray too far from their origin. This is intentional behavior so that you're not constantly rebasing the scene.

This is how I set up my player: (I set the movement to 1000 when I was testing so it would trigger a rebase more quickly) Also it shouldn't matter whether it's client auth or not since this package is designed to work with server auth and it works with both.
![image](https://user-images.githubusercontent.com/44267994/204174034-67f936c5-2028-4a34-bcf9-ea856c58fea0.png)

This is how I set up the Network Manager:
![image](https://user-images.githubusercontent.com/44267994/204174232-58441dff-e783-4e1f-b3e6-c35fe92c4b30.png)

This is the scene hierarchy: (I would recommend having a separate Gameplay scene for players and a Managers scene for the NetworkManager, but it should work with just one scene as well as long as your NM is set to Destroy Newest.
![image](https://user-images.githubusercontent.com/44267994/204174140-a98cc227-1103-4756-ae07-2836807affb7.png)

**Comment by hudmarc** [comment]
Provided more example screenshots and explanations on how the various components work.

**Comment by yajiedesign** [comment]
> I just set up the scene like you described and it seems to work correctly on my end. I have added the FO provided Network Manager, and a Player Spawner component to that NetworkManager. This player is the default FishNet capsule set to a 1000x move rate on a huge plane. Whenever the player goes too far from the origin they are rebased. Is Auto Register set to true on your FOObserver? Also, the player will not stay at 0,0,0 always, they are only rebased when they stray too far from their origin. This is intentional behavior so that you're not constantly rebasing the scene.
> 
> This is how I set up my player: (I set the movement to 1000 when I was testing so it would trigger a rebase more quickly) Also it shouldn't matter whether it's client auth or not since this package is designed to work with server auth and it works with both. ![image](https://user-images.githubusercontent.com/44267994/204174034-67f936c5-2028-4a34-bcf9-ea856c58fea0.png)
> 
> This is how I set up the Network Manager: ![image](https://user-images.githubusercontent.com/44267994/204174232-58441dff-e783-4e1f-b3e6-c35fe92c4b30.png)
> 
> This is the scene hierarchy: (I would recommend having a separate Gameplay scene for players and a Managers scene for the NetworkManager, but it should work with just one scene as well as long as your NM is set to Destroy Newest. ![image](https://user-images.githubusercontent.com/44267994/204174140-a98cc227-1103-4756-ae07-2836807affb7.png)

i have same problem,after debug i think key is client authoritative.it must false.
